import json
import os
import sys

# Template based on Typora export from about.html
HTML_TEMPLATE = r'''<!doctype html>
<html>
<head>
<meta charset='UTF-8'><meta name='viewport' content='width=device-width initial-scale=1'>
<link href='https://fonts.loli.net/css?family=Open+Sans:400italic,700italic,700,400&subset=latin,latin-ext' rel='stylesheet' type='text/css' />
<style type='text/css'>
html {overflow-x: initial !important;}:root { --bg-color:#ffffff; --text-color:#333333; --select-text-bg-color:#B5D6FC; --select-text-font-color:auto; --monospace:"Lucida Console",Consolas,"Courier",monospace; --title-bar-height:20px; }
.mac-os-11 { --title-bar-height:28px; }
html { font-size: 14px; background-color: var(--bg-color); color: var(--text-color); font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; -webkit-font-smoothing: antialiased; }
body { margin: 0px; padding: 0px; height: auto; inset: 0px; font-size: 1rem; line-height: 1.42857; overflow-x: hidden; background: inherit; tab-size: 4; }
#write { margin: 0px auto; height: auto; width: inherit; word-break: normal; overflow-wrap: break-word; position: relative; white-space: normal; overflow-x: visible; padding-top: 36px; padding-bottom: 100px; max-width: 860px; padding-left: 30px; padding-right: 30px;}
img { max-width: 100%; vertical-align: middle; image-orientation: from-image; }
h1, h2, h3, h4, h5, h6 { position: relative; margin-top: 1rem; margin-bottom: 1rem; font-weight: bold; line-height: 1.4; cursor: text; }
h1 { font-size: 2.25em; line-height: 1.2; border-bottom: 1px solid #eee; }
h2 { font-size: 1.75em; line-height: 1.225; border-bottom: 1px solid #eee; }
h3 { font-size: 1.5em; line-height: 1.43; }
p { margin-top: 1rem; margin-bottom: 1rem; }
table { border-collapse: collapse; border-spacing: 0px; width: 100%; overflow: auto; break-inside: auto; text-align: left; margin-top: 1rem; margin-bottom: 1rem; }
table tr { border: 1px solid #dfe2e5; margin: 0; padding: 0; }
table tr:nth-child(2n) { background-color: #f8f8f8; }
table th, table td { border: 1px solid #dfe2e5; padding: 6px 13px; }
pre, code { font-family: var(--monospace); background-color: #f8f8f8; border-radius: 3px; }
pre { padding: 10px; overflow-x: auto; white-space: pre-wrap; border: 1px solid #e7eaed; }
code { background-color: #f3f4f4; padding: 2px 4px; }
</style>
<title>Function Database</title>
</head>
<body class='typora-export'>
<div id='write'>
{{content}}
</div>
</body>
</html>
'''

def generate_functions_html(json_path, output_html_path, image_dir):
    with open(json_path, 'r') as f:
        data = json.load(f)

    body_content = "<h1>Function Database</h1>\n"
    body_content += "<p>This is a reference for the built-in 2D curves available in <strong>fũnkplot</strong>.</p>\n\n"

    # Organize by category
    categories = {cat["name"]: cat["description"] for cat in data["categories"]}
    curves_by_cat = {}
    for curve in data["curves"]:
        cat = curve.get("category", "general")
        if cat not in curves_by_cat:
            curves_by_cat[cat] = []
        curves_by_cat[cat].append(curve)

    for cat_name in sorted(curves_by_cat.keys()):
        cat_desc = categories.get(cat_name, cat_name.capitalize())
        body_content += f"<h2>{cat_desc}</h2>\n\n"
        
        for curve in curves_by_cat[cat_name]:
            name = curve["name"]
            key = curve["key"]
            desc = curve.get("description", "")
            
            body_content += f"<h3>{name}</h3>\n\n"
            if desc:
                body_content += f"<p>{desc}</p>\n\n"
            
            # Formula image (key.png)
            formula_img = os.path.join(image_dir, f"{key}.png")
            if os.path.exists(formula_img):
                body_content += f"<p><strong>Equation:</strong></p>\n<p><img src='{formula_img}' alt='{name} formula'></p>\n\n"
            
            # Plot image (key.g.png)
            plot_img = os.path.join(image_dir, f"{key}.g.png")
            if os.path.exists(plot_img):
                body_content += f"<p><strong>Plot:</strong></p>\n<p><img src='{plot_img}' alt='{name} plot'></p>\n\n"
            
            # Example code (from .fnk file generated by builtins.py)
            fnk_path = os.path.join(image_dir, f"{key}.fnk")
            if os.path.exists(fnk_path):
                body_content += "<p><strong>Example Code:</strong></p>\n<pre><code>"
                with open(fnk_path, 'r') as fnk_f:
                    body_content += fnk_f.read().replace("<", "&lt;").replace(">", "&gt;")
                body_content += "</code></pre>\n\n"
            
            body_content += "<hr>\n\n"

    final_html = HTML_TEMPLATE.replace("{{content}}", body_content)
    with open(output_html_path, 'w') as f:
        f.write(final_html)

if __name__ == "__main__":
    if len(sys.argv) < 4:
        print("Usage: gen_function_db.py <json_path> <output_html_path> <image_dir>")
        sys.exit(1)
    
    generate_functions_html(sys.argv[1], sys.argv[2], sys.argv[3])
