name: CMake and AppImage Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build-linux:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          wget equivs devscripts debhelper \
          qtbase5-dev qtdeclarative5-dev qtmultimedia5-dev \
          qtscript5-dev libqt5opengl5-dev libqt5x11extras5-dev \
          qtxmlpatterns5-dev-tools libqt5webkit5-dev qtwebengine5-dev \
          libqt5svg5-dev qttools5-dev libqt5help5 \
          qtbase5-private-dev cmake git pkg-config build-essential \
          libpython3-dev mesa-common-dev python3 latex2rtf

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build Project
      run: cmake --build build --config ${{env.BUILD_TYPE}}

    - name: Install to AppDir
      run: make -C build install DESTDIR=${{github.workspace}}/AppDir

    - name: Copy Desktop Entry and Icon
      run: |
        mkdir -p AppDir/usr/share/icons/hicolor/256x256/apps
        mkdir -p AppDir/usr/share/applications
        cp debian/funkplot-gui.desktop AppDir/usr/share/applications/
        cp debian/funkplot-gui.png AppDir/usr/share/icons/hicolor/256x256/apps/

    - name: Download and Run linuxdeployqt
      run: |
        cd ${{github.workspace}}
        wget -nv -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
        chmod +x linuxdeployqt-continuous-x86_64.AppImage
        ./linuxdeployqt-continuous-x86_64.AppImage AppDir/usr/local/bin/funkplot-gui \
          -appimage \
          -unsupported-bundle-everything \
          -unsupported-allow-new-glibc \
          -verbose=2 \
          -extra-plugins=iconengines,platformthemes/libqgtk3.so,platforms

    - name: Upload AppImage
      uses: actions/upload-artifact@v4
      with:
        name: funkplot-appimage
        path: |
          build/*.AppImage
